authenticationCachePolicy: "maximumSize=10000, expireAfterAccess=10m"
database:
  driverClass: org.h2.Driver
  url: jdbc:h2:./target/rufusdb
logging:
  appenders:
    -
      target: stdout
      threshold: ALL
      timeZone: UTC
      type: console
  level: INFO
