authenticationCachePolicy: "maximumSize=10000, expireAfterAccess=10m"
database:
  driverClass: org.postgresql.Driver
  url: "jdbc:postgresql:rufusdb"
logging:
  appenders:
    -
      target: stdout
      threshold: ALL
      timeZone: UTC
      type: console
  level: INFO